<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\VideoModule\Form;

use MU\VideoModule\Form\Base\AbstractGetVideosType;

/**
 * Configuration form type implementation class.
 */
class GetVideosType extends AbstractGetVideosType
{
    // feel free to extend the base form type class here
}
