<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\VideoModule\Form\Type;

use MU\VideoModule\Form\Type\Base\AbstractMovieType;

/**
 * Movie editing form type implementation class.
 */
class MovieType extends AbstractMovieType
{
    // feel free to extend the movie editing form type class here
}
