<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Upload handler implementation class.
 */
class MUVideo_UploadHandler extends MUVideo_Base_UploadHandler
{
    /**
     * Constructor initialising the supported object types.
     */
    public function __construct()
    {
        parent::__construct();
        $this->allowedFileSizes = array('movie' => array('uploadOfMovie' => ModUtil::getVar('MUVideo', 'maxSizeOfMovie', 1024000000), 'poster' => ModUtil::getVar('MUVideo', 'maxSizeOfPoster', 102400)));
    }
}
