<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de) at Tue May 06 22:49:35 CEST 2014.
 */

/**
 * Version information implementation class.
 */
class MUVideo_Version extends MUVideo_Base_Version
{
    /**
     * Retrieves meta data information for this application.
     *
     * @return array List of meta data.
     */
    public function getMetaData()
    {
        $meta = parent::getMetaData();
        
        // the current module version
        $meta['version']              = '1.0.0';
        // the displayed name of the module
        $meta['displayname']          = $this->__('MUVideo');
        // the module description
        $meta['description']          = $this->__('MUVideo module is a module to handle Videos.');
        //! url version of name, should be in lowercase without space
        $meta['url']                  = $this->__('muvideo');

        return $meta;
    }
}
