<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

include_once 'Needles/Base/Abstractcollection_info.php';

/**
 * MUVideo collection needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUVideo_needleapi_collection_info()
{
    return MUVideo_needleapi_collection_baseInfo();
}
