<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This class provides object meta data for the Tag module.
 */
class MUVideo_TaggedObjectMeta_MUVideo extends MUVideo_TaggedObjectMeta_Base_AbstractMUVideo
{
    // feel free to extend the tag support here
}
