<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the mUVideo_collection_getVideos() function.
 * It aims on the collection object type.
 */
class MUVideo_Form_Handler_Collection_GetVideos extends MUVideo_Form_Handler_Collection_Base_GetVideos
{
    // feel free to extend the base handler class here
}
