<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Validator class for encapsulating entity validation methods.
 *
 * This is the base validation class for movie entities.
 */
class MUVideo_Entity_Validator_Base_Movie extends MUVideo_Validator
{
    /**
     * Performs all validation rules.
     *
     * @return mixed either array with error information or true on success
     */
    public function validateAll()
    {
        $errorInfo = array(
            'message' => '',
            'code' => 0,
            'debugArray' => array()
        );
        $dom = ZLanguage::getModuleDomain('MUVideo');
        if (!$this->isStringNotEmpty('workflowState')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('workflow state'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('title', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('title', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotEmpty('title')) {
            $errorInfo['message'] = __f('Error! Field value must not be empty (%s).', array('title'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('description', 4000)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('description', 4000), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('uploadOfMovie', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('upload of movie', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('urlOfYoutube', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('url of youtube', 255), $dom);
            return $errorInfo;
        }
        if ($this->entity['urlOfYoutube'] != '' && !$this->isValidUrl('urlOfYoutube')) {
            $errorInfo['message'] = __f('Error! Field value must be a valid url (%s).', array('url of youtube'), $dom);
            return $errorInfo;
        }
        if (!$this->isStringNotLongerThan('poster', 255)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('poster', 255), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('widthOfMovie')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('width of movie'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotEmpty('widthOfMovie')) {
            $errorInfo['message'] = __f('Error! Field value must not be 0 (%s).', array('width of movie'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('widthOfMovie', 11)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('width of movie', 11), $dom);
            return $errorInfo;
        }
        if (!$this->isValidInteger('heightOfMovie')) {
            $errorInfo['message'] = __f('Error! Field value may only contain digits (%s).', array('height of movie'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotEmpty('heightOfMovie')) {
            $errorInfo['message'] = __f('Error! Field value must not be 0 (%s).', array('height of movie'), $dom);
            return $errorInfo;
        }
        if (!$this->isNumberNotLongerThan('heightOfMovie', 11)) {
            $errorInfo['message'] = __f('Error! Length of field value must not be higher than %2$s (%1$s).', array('height of movie', 11), $dom);
            return $errorInfo;
        }
    
        return true;
    }
    
    /**
     * Checks for unique values.
     *
     * This method determines if there already exist movies with the same movie.
     *
     * @param string $fieldName The name of the property to be checked
     *
     * @return boolean result of this check, true if the given movie does not already exist
     */
    public function isUniqueValue($fieldName)
    {
        if ($this->entity[$fieldName] === '') {
            return false;
        }
    
        $entityClass = 'MUVideo_Entity_Movie';
        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');
        $repository = $entityManager->getRepository($entityClass);
    
        $excludeid = $this->entity['id'];
    
        return $repository->detectUniqueState($fieldName, $this->entity[$fieldName], $excludeid);
    }
    
    /**
     * Gets the entity.
     *
     * @return Zikula_EntityAccess
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Sets the entity.
     *
     * @param Zikula_EntityAccess $entity
     *
     * @return void
     */
    public function setEntity(Zikula_EntityAccess $entity = null)
    {
        $this->entity = $entity;
    }
    
}
