<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\VideoModule\Event;

use MU\VideoModule\Event\Base\AbstractFilterMovieEvent;

/**
 * Event implementation class for filtering movie processing.
 */
class FilterMovieEvent extends AbstractFilterMovieEvent
{
    // feel free to extend the event class here
}
