<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the mUVideo_movie_edit() function.
 * It aims on the movie object type.
 */
class MUVideo_Form_Handler_Movie_Edit extends MUVideo_Form_Handler_Movie_Base_Edit
{
    // feel free to extend the base handler class here
}
