<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\VideoModule\Api\Base;

use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;
use Zikula_AbstractBase;

/**
 * Mailz api base class.
 */
abstract class AbstractMailzApi extends Zikula_AbstractBase implements ContainerAwareInterface
{
    use ContainerAwareTrait;

    /**
     * MailzApi constructor.
     */
    public function __construct()
    {
        $this->setContainer(\ServiceUtil::getManager());
    }

    /**
     * Returns existing Mailz plugins with type / title.
     *
     * @param array $args List of arguments
     *
     * @return array List of provided plugin functions
     */
    public function getPlugins(array $args = [])
    {
        $translator = $this->container->get('translator.default');
    
        $plugins = [];
        $plugins[] = [
            'pluginid'      => 1,
            'module'        => 'MUVideoModule',
            'title'         => $translator->__('3 newest collections'),
            'description'   => $translator->__('A list of the three newest collections.')
        ];
        $plugins[] = [
            'pluginid'      => 2,
            'module'        => 'MUVideoModule',
            'title'         => $translator->__('3 random collections'),
            'description'   => $translator->__('A list of three random collections.')
        ];
    
        return $plugins;
    }
    
    /**
     * Returns the content for a given Mailz plugin.
     *
     * @param array    $args                List of arguments
     * @param int      $args['pluginid']    id number of plugin (internal id for this module, see getPlugins method)
     * @param string   $args['params']      optional, show specific one or all otherwise
     * @param int      $args['uid']         optional, user id for user specific content
     * @param string   $args['contenttype'] h or t for html or text
     * @param datetime $args['last']        timestamp of last newsletter
     *
     * @return string output of plugin template
     */
    public function getContent(array $args = [])
    {
        // $args is something like:
        // Array ( [uid] => 5 [contenttype] => h [pluginid] => 1 [nid] => 1 [last] => 0000-00-00 00:00:00 [params] => Array ( [] => ) ) 1
        $objectType = 'collection';
    
        $entityFactory = $this->container->get('mu_video_module.entity_factory');
        $idFields = $entityFactory->getIdFields($objectType);
        $repository = $entityFactory->getRepository($objectType);
    
        $sortParam = '';
        if ($args['pluginid'] == 2) {
            $sortParam = 'RAND()';
        } elseif ($args['pluginid'] == 1) {
            if (count($idFields) == 1) {
                $sortParam = $idFields[0] . ' DESC';
            } else {
                foreach ($idFields as $idField) {
                    if (!empty($sortParam)) {
                        $sortParam .= ', ';
                    }
                    $sortParam .= $idField . ' ASC';
                }
            }
        }
    
        $where = ''/*$this->filter*/;
        $resultsPerPage = 3;
    
        // get objects from database
        list($entities, $objectCount) = $repository->selectWherePaginated($where, $orderBy, 1, $resultsPerPage);
    
        $templateType = $args['contenttype'] == 't' ? 'text' : 'html';
    
        //$templateParameters = ['sorting' => $this->sorting, 'amount' => $this->amount, 'filter' => $this->filter, 'template' => $this->template];
        $templateParameters = [
            'objectType' => $objectType,
            'items' => $entities
        ];
        $imageHelper = $this->container->get('mu_video_module.image_helper');
        $templateParameters = array_merge($templateParameters, $repository->getAdditionalTemplateParameters($imageHelper, 'api', ['name' => 'mailz']));
    
        return $this->container->get('twig')->render(
            '@MUVideoModule/Mailz/itemlist_' . $objectType . $templateType . '.twig',
            $templateParameters
        );
    }
}
