<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

include_once 'Needles/Base/Abstractcollection_info.php';

/**
 * MUVideoModule collection needle information.
 *
 * @param none
 *
 * @return string with short usage description
 */
function MUVideoModule_needleapi_collection_info()
{
    return MUVideoModule_needleapi_collection_baseInfo();
}
