<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

use Gedmo\Translatable\Entity\AbstractTranslation;

/**
 * Entity extension domain class storing movie translations.
 *
 * This is the base translation class for movie entities.
 */
abstract class MUVideo_Entity_Base_AbstractMovieTranslation extends AbstractTranslation
{
}
