<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Abstract object selector plugin implementation class.
 */
abstract class MUVideo_Form_Plugin_AbstractObjectSelector extends MUVideo_Form_Plugin_Base_AbstractObjectSelector
{
    // feel free to add your customisation here
}
