<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\VideoModule\HookSubscriber;

use MU\VideoModule\HookSubscriber\Base\AbstractMovieFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class MovieFormAwareHookSubscriber extends AbstractMovieFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
