<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace MU\VideoModule\HookSubscriber;

use MU\VideoModule\HookSubscriber\Base\AbstractMovieUiHooksSubscriber;

/**
 * Implementation class for ui hooks subscriber.
 */
class MovieUiHooksSubscriber extends AbstractMovieUiHooksSubscriber
{
    // feel free to add your own convenience methods here
}
