<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Collection controller class providing navigation and interaction functionality.
 */
class MUVideo_Controller_Collection extends MUVideo_Controller_Base_Collection
{
    /**
     * This method takes care of the application configuration.
     *
     * @return string Output
     */
    public function getVideos()
    {
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN));
        
        // Create new Form reference
        $view = \FormUtil::newForm($this->name, $this);
        
        $templateName = 'collection/getVideos.tpl';
        
        // Execute form using supplied template and page event handler
        return $view->execute($templateName, new MUVideo_Form_Handler_Collection_GetVideos());
    }
}
