<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Paginator switch implementation class for making 1.3.x modules work with 1.4.
 */
class MUVideo_Paginator_Paginator extends MUVideo_Paginator_Base_Paginator
{
    // extend the paginator class here if desired
}
