services:
    # Event subscribers and listeners
    mu_video_module.entity_lifecycle_listener:
        class: MU\VideoModule\Listener\EntityLifecycleListener
        arguments:
            - "@service_container"
            - "@event_dispatcher"
            - "@logger"
        tags:
            - { name: doctrine.event_subscriber }
    
    mu_video_module.kernel_listener:
        class: MU\VideoModule\Listener\KernelListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.installer_listener:
        class: MU\VideoModule\Listener\InstallerListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.moduledispatch_listener:
        class: MU\VideoModule\Listener\ModuleDispatchListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.mailer_listener:
        class: MU\VideoModule\Listener\MailerListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.theme_listener:
        class: MU\VideoModule\Listener\ThemeListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.userlogin_listener:
        class: MU\VideoModule\Listener\UserLoginListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.userlogout_listener:
        class: MU\VideoModule\Listener\UserLogoutListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.user_listener:
        class: MU\VideoModule\Listener\UserListener
        arguments:
            - "@translator.default"
            - "@mu_video_module.entity_factory"
            - "@zikula_users_module.current_user"
            - "@logger"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.userregistration_listener:
        class: MU\VideoModule\Listener\UserRegistrationListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.users_listener:
        class: MU\VideoModule\Listener\UsersListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.group_listener:
        class: MU\VideoModule\Listener\GroupListener
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.thirdparty_listener:
        class: MU\VideoModule\Listener\ThirdPartyListener
        arguments:
            - "@filesystem"
            - "@request_stack"
        tags:
            - { name: kernel.event_subscriber }
    
    mu_video_module.workflow_events_listener:
        class: MU\VideoModule\Listener\WorkflowEventsListener
        arguments:
            - "@zikula_permissions_module.api.permission"
        tags:
            - { name: kernel.event_subscriber }
    
