services:
    # Form types
    
    mu_video_module.form.type.collectionquicknav:
        class: MU\VideoModule\Form\Type\QuickNavigation\CollectionQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_video_module.listentries_helper"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.moviequicknav:
        class: MU\VideoModule\Form\Type\QuickNavigation\MovieQuickNavType
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@mu_video_module.entity_display_helper"
            - "@mu_video_module.listentries_helper"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.playlistquicknav:
        class: MU\VideoModule\Form\Type\QuickNavigation\PlaylistQuickNavType
        arguments:
            - "@translator.default"
            - "@mu_video_module.listentries_helper"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.handler.collection:
        class: MU\VideoModule\Form\Handler\Collection\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@mu_video_module.entity_factory"
            - "@mu_video_module.controller_helper"
            - "@mu_video_module.model_helper"
            - "@mu_video_module.workflow_helper"
            - "@mu_video_module.hook_helper"
            - "@mu_video_module.translatable_helper"
            - "@mu_video_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.collection:
        class: MU\VideoModule\Form\Type\CollectionType
        arguments:
            - "@translator.default"
            - "@mu_video_module.entity_factory"
            - "@mu_video_module.collection_filter_helper"
            - "@mu_video_module.entity_display_helper"
            - "@zikula_extensions_module.api.variable"
            - "@mu_video_module.translatable_helper"
            - "@mu_video_module.listentries_helper"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.handler.movie:
        class: MU\VideoModule\Form\Handler\Movie\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@mu_video_module.entity_factory"
            - "@mu_video_module.controller_helper"
            - "@mu_video_module.model_helper"
            - "@mu_video_module.workflow_helper"
            - "@mu_video_module.hook_helper"
            - "@mu_video_module.translatable_helper"
            - "@mu_video_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.movie:
        class: MU\VideoModule\Form\Type\MovieType
        arguments:
            - "@translator.default"
            - "@mu_video_module.entity_factory"
            - "@mu_video_module.collection_filter_helper"
            - "@mu_video_module.entity_display_helper"
            - "@zikula_extensions_module.api.variable"
            - "@mu_video_module.translatable_helper"
            - "@mu_video_module.listentries_helper"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.handler.playlist:
        class: MU\VideoModule\Form\Handler\Playlist\EditHandler
        arguments:
            - "@kernel"
            - "@translator.default"
            - "@form.factory"
            - "@request_stack"
            - "@router"
            - "@logger"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.current_user"
            - "@mu_video_module.entity_factory"
            - "@mu_video_module.controller_helper"
            - "@mu_video_module.model_helper"
            - "@mu_video_module.workflow_helper"
            - "@mu_video_module.hook_helper"
            - "@mu_video_module.translatable_helper"
            - "@mu_video_module.feature_activation_helper"
        calls:
            - [setLockingApi, ["@?zikula_pagelock_module.api.locking"]]
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.playlist:
        class: MU\VideoModule\Form\Type\PlaylistType
        arguments:
            - "@translator.default"
            - "@mu_video_module.entity_factory"
            - "@zikula_extensions_module.api.variable"
            - "@mu_video_module.translatable_helper"
            - "@mu_video_module.listentries_helper"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.block.itemlist:
        class: MU\VideoModule\Block\Form\Type\ItemListBlockType
        arguments:
            - "@translator.default"
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.collectionfinder:
        class: MU\VideoModule\Form\Type\Finder\CollectionFinderType
        arguments:
            - "@translator.default"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.moviefinder:
        class: MU\VideoModule\Form\Type\Finder\MovieFinderType
        arguments:
            - "@translator.default"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.playlistfinder:
        class: MU\VideoModule\Form\Type\Finder\PlaylistFinderType
        arguments:
            - "@translator.default"
            - "@mu_video_module.feature_activation_helper"
        tags:
            - { name: form.type }
    
    mu_video_module.form.type.config:
        class: MU\VideoModule\Form\Type\ConfigType
        arguments:
            - "@translator.default"
            - "@mu_video_module.listentries_helper"
        tags:
            - { name: form.type }
            
    mu_video_module.form.type.getvideos:
        class: MU\VideoModule\Form\Type\GetVideosType
        arguments:
            - "@translator.default"
            - "@=service('zikula_extensions_module.api.variable').getAll('MUVideoModule')"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: form.type }
            
    mu_video_module.form.type.getplaylists:
        class: MU\VideoModule\Form\Type\GetPlaylistsType
        arguments:
            - "@translator.default"
            - "@=service('zikula_extensions_module.api.variable').getAll('MUVideoModule')"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
        tags:
            - { name: form.type }
