services:
    mu_video_module.hook_subscriber.filter_hooks.collections:
        class: MU\VideoModule\HookSubscriber\CollectionFilterHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.filter_hooks.collections' }

    mu_video_module.hook_subscriber.form_aware_hook.collections:
        class: MU\VideoModule\HookSubscriber\CollectionFormAwareHookSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.form_aware_hook.collections' }

    mu_video_module.hook_subscriber.ui_hooks.collections:
        class: MU\VideoModule\HookSubscriber\CollectionUiHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.ui_hooks.collections' }

    mu_video_module.hook_subscriber.filter_hooks.movies:
        class: MU\VideoModule\HookSubscriber\MovieFilterHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.filter_hooks.movies' }

    mu_video_module.hook_subscriber.form_aware_hook.movies:
        class: MU\VideoModule\HookSubscriber\MovieFormAwareHookSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.form_aware_hook.movies' }

    mu_video_module.hook_subscriber.ui_hooks.movies:
        class: MU\VideoModule\HookSubscriber\MovieUiHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.ui_hooks.movies' }

    mu_video_module.hook_subscriber.filter_hooks.playlists:
        class: MU\VideoModule\HookSubscriber\PlaylistFilterHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.filter_hooks.playlists' }

    mu_video_module.hook_subscriber.form_aware_hook.playlists:
        class: MU\VideoModule\HookSubscriber\PlaylistFormAwareHookSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.form_aware_hook.playlists' }

    mu_video_module.hook_subscriber.ui_hooks.playlists:
        class: MU\VideoModule\HookSubscriber\PlaylistUiHooksSubscriber
        arguments:
            - "@translator.default"
        tags:
            - { name: zikula.hook_subscriber, areaName: 'subscriber.muvideomodule.ui_hooks.playlists' }

    mu_video_module.hook_provider.filter_hooks.provider:
        class: MU\VideoModule\HookProvider\FilterHooksProvider
        arguments:
            - "@translator.default"
            - "@mu_video_module.entity_factory"
        tags:
            - { name: zikula.hook_provider, areaName: 'provider.muvideomodule.filter_hooks.video' }

