services:
    # Twig extension
    mu_video_module.twig_extension:
        class: MU\VideoModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_users_module.user_repository"
            - "@mu_video_module.workflow_helper"
            - "@mu_video_module.listentries_helper"
        public: false
        tags:
            - { name: twig.extension }
