services:
    # Custom validators
    mu_video_module.validator.list_entry.validator:
        class: MU\VideoModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@mu_video_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: mu_video_module.validator.list_entry.validator }
