<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link http://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\VideoModule\Form\Type\Finder;

use MU\VideoModule\Form\Type\Finder\Base\AbstractPlaylistFinderType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Playlist finder form type implementation class.
 */
class PlaylistFinderType extends AbstractPlaylistFinderType
{
    /**
     * Adds a "paste as" field.
     *
     * @param FormBuilderInterface $builder The form builder
     * @param array                $options The options
     */
    public function addPasteAsField(FormBuilderInterface $builder, array $options)
    {
        $builder->add('pasteAs', ChoiceType::class, [
            'label' => $this->__('Paste as') . ':',
            'empty_data' => 1,
            'choices' => [
                $this->__('Relative link to the playlist') => 1,
                $this->__('Absolute url to the playlist') => 2,
                $this->__('Playlist') => 4
            ],
            'choices_as_values' => true,
            'multiple' => false,
            'expanded' => false
        ]);
    }
}
