<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

namespace \Form\Type\Finder;

use \Form\Type\Finder\Base\PlaylistFinderType as BasePlaylistFinderType;

/**
 * Playlist finder form type implementation class.
 */
class PlaylistFinderType extends BasePlaylistFinderType
{
    // feel free to extend the base form type class here
}
