modules/MUVideo/templates/collection/main.tpl: config/templates/MUVideo/collection/main.tpl
modules/MUVideo/templates/collection/view.tpl: config/templates/MUVideo/collection/view.tpl
modules/MUVideo/templates/collection/viewQuickNav.tpl: config/templates/MUVideo/collection/viewQuickNav.tpl
modules/MUVideo/templates/collection/view.csv.tpl: config/templates/MUVideo/collection/view.csv.tpl
modules/MUVideo/templates/collection/view.rss.tpl: config/templates/MUVideo/collection/view.rss.tpl
modules/MUVideo/templates/collection/view.atom.tpl: config/templates/MUVideo/collection/view.atom.tpl
modules/MUVideo/templates/collection/view.json.tpl: config/templates/MUVideo/collection/view.json.tpl
modules/MUVideo/templates/collection/display.json.tpl: config/templates/MUVideo/collection/display.json.tpl
modules/MUVideo/templates/collection/display.tpl: config/templates/MUVideo/collection/display.tpl
modules/MUVideo/templates/collection/delete.tpl: config/templates/MUVideo/collection/delete.tpl
modules/MUVideo/templates/movie/main.tpl: config/templates/MUVideo/movie/main.tpl
modules/MUVideo/templates/movie/view.tpl: config/templates/MUVideo/movie/view.tpl
modules/MUVideo/templates/movie/viewQuickNav.tpl: config/templates/MUVideo/movie/viewQuickNav.tpl
modules/MUVideo/templates/movie/view.csv.tpl: config/templates/MUVideo/movie/view.csv.tpl
modules/MUVideo/templates/movie/view.rss.tpl: config/templates/MUVideo/movie/view.rss.tpl
modules/MUVideo/templates/movie/view.atom.tpl: config/templates/MUVideo/movie/view.atom.tpl
modules/MUVideo/templates/movie/view.json.tpl: config/templates/MUVideo/movie/view.json.tpl
modules/MUVideo/templates/movie/display.json.tpl: config/templates/MUVideo/movie/display.json.tpl
modules/MUVideo/templates/movie/display.tpl: config/templates/MUVideo/movie/display.tpl
modules/MUVideo/templates/movie/delete.tpl: config/templates/MUVideo/movie/delete.tpl
modules/MUVideo/templates/movie/includeDisplayItemListOne.tpl: config/templates/MUVideo/movie/includeDisplayItemListOne.tpl
modules/MUVideo/templates/movie/includeDisplayItemListMany.tpl: config/templates/MUVideo/movie/includeDisplayItemListMany.tpl
modules/MUVideo/templates/playlist/main.tpl: config/templates/MUVideo/playlist/main.tpl
modules/MUVideo/templates/playlist/view.tpl: config/templates/MUVideo/playlist/view.tpl
modules/MUVideo/templates/playlist/viewQuickNav.tpl: config/templates/MUVideo/playlist/viewQuickNav.tpl
modules/MUVideo/templates/playlist/view.csv.tpl: config/templates/MUVideo/playlist/view.csv.tpl
modules/MUVideo/templates/playlist/view.rss.tpl: config/templates/MUVideo/playlist/view.rss.tpl
modules/MUVideo/templates/playlist/view.atom.tpl: config/templates/MUVideo/playlist/view.atom.tpl
modules/MUVideo/templates/playlist/view.json.tpl: config/templates/MUVideo/playlist/view.json.tpl
modules/MUVideo/templates/playlist/delete.tpl: config/templates/MUVideo/playlist/delete.tpl
modules/MUVideo/templates/playlist/includeDisplayItemListOne.tpl: config/templates/MUVideo/playlist/includeDisplayItemListOne.tpl
modules/MUVideo/templates/playlist/includeDisplayItemListMany.tpl: config/templates/MUVideo/playlist/includeDisplayItemListMany.tpl
modules/MUVideo/templates/admin/header.tpl: config/templates/MUVideo/admin/header.tpl
modules/MUVideo/templates/admin/footer.tpl: config/templates/MUVideo/admin/footer.tpl
modules/MUVideo/templates/user/header.tpl: config/templates/MUVideo/user/header.tpl
modules/MUVideo/templates/user/footer.tpl: config/templates/MUVideo/user/footer.tpl
modules/MUVideo/templates/admin/inlineRedirectHandler.tpl: config/templates/MUVideo/admin/inlineRedirectHandler.tpl
modules/MUVideo/templates/user/inlineRedirectHandler.tpl: config/templates/MUVideo/user/inlineRedirectHandler.tpl
modules/MUVideo/templates/collection/edit.tpl: config/templates/MUVideo/collection/edit.tpl
modules/MUVideo/templates/collection/inlineRedirectHandler.tpl: config/templates/MUVideo/collection/inlineRedirectHandler.tpl
modules/MUVideo/templates/movie/edit.tpl: config/templates/MUVideo/movie/edit.tpl
modules/MUVideo/templates/movie/inlineRedirectHandler.tpl: config/templates/MUVideo/movie/inlineRedirectHandler.tpl
modules/MUVideo/templates/playlist/edit.tpl: config/templates/MUVideo/playlist/edit.tpl
modules/MUVideo/templates/playlist/inlineRedirectHandler.tpl: config/templates/MUVideo/playlist/inlineRedirectHandler.tpl
modules/MUVideo/templates/helper/includeCategoriesDisplay.tpl: config/templates/MUVideo/helper/includeCategoriesDisplay.tpl
modules/MUVideo/templates/helper/includeCategoriesEdit.tpl: config/templates/MUVideo/helper/includeCategoriesEdit.tpl
modules/MUVideo/templates/helper/includeStandardFieldsDisplay.tpl: config/templates/MUVideo/helper/includeStandardFieldsDisplay.tpl
modules/MUVideo/templates/helper/includeStandardFieldsEdit.tpl: config/templates/MUVideo/helper/includeStandardFieldsEdit.tpl
modules/MUVideo/templates/admin/config.tpl: config/templates/MUVideo/admin/config.tpl
modules/MUVideo/templates/includePdfHeader.tpl: config/templates/MUVideo/includePdfHeader.tpl
