src/modules/MUVideo/templates/collection/main.tpl: config/templates/MUVideo/collection/main.tpl
src/modules/MUVideo/templates/collection/view.tpl: config/templates/MUVideo/collection/view.tpl
src/modules/MUVideo/templates/collection/view_quickNav.tpl: config/templates/MUVideo/collection/view_quickNav.tpl
src/modules/MUVideo/templates/collection/view.csv.tpl: config/templates/MUVideo/collection/view.csv.tpl
src/modules/MUVideo/templates/collection/view.rss.tpl: config/templates/MUVideo/collection/view.rss.tpl
src/modules/MUVideo/templates/collection/view.atom.tpl: config/templates/MUVideo/collection/view.atom.tpl
src/modules/MUVideo/templates/collection/view.json.tpl: config/templates/MUVideo/collection/view.json.tpl
src/modules/MUVideo/templates/collection/display.json.tpl: config/templates/MUVideo/collection/display.json.tpl
src/modules/MUVideo/templates/collection/display.tpl: config/templates/MUVideo/collection/display.tpl
src/modules/MUVideo/templates/collection/delete.tpl: config/templates/MUVideo/collection/delete.tpl
src/modules/MUVideo/templates/collection/include_displayItemListOne.tpl: config/templates/MUVideo/collection/include_displayItemListOne.tpl
src/modules/MUVideo/templates/collection/include_displayItemListMany.tpl: config/templates/MUVideo/collection/include_displayItemListMany.tpl
src/modules/MUVideo/templates/movie/main.tpl: config/templates/MUVideo/movie/main.tpl
src/modules/MUVideo/templates/movie/view.tpl: config/templates/MUVideo/movie/view.tpl
src/modules/MUVideo/templates/movie/view_quickNav.tpl: config/templates/MUVideo/movie/view_quickNav.tpl
src/modules/MUVideo/templates/movie/view.csv.tpl: config/templates/MUVideo/movie/view.csv.tpl
src/modules/MUVideo/templates/movie/view.rss.tpl: config/templates/MUVideo/movie/view.rss.tpl
src/modules/MUVideo/templates/movie/view.atom.tpl: config/templates/MUVideo/movie/view.atom.tpl
src/modules/MUVideo/templates/movie/view.json.tpl: config/templates/MUVideo/movie/view.json.tpl
src/modules/MUVideo/templates/movie/display.json.tpl: config/templates/MUVideo/movie/display.json.tpl
src/modules/MUVideo/templates/movie/display.tpl: config/templates/MUVideo/movie/display.tpl
src/modules/MUVideo/templates/movie/delete.tpl: config/templates/MUVideo/movie/delete.tpl
src/modules/MUVideo/templates/movie/include_displayItemListOne.tpl: config/templates/MUVideo/movie/include_displayItemListOne.tpl
src/modules/MUVideo/templates/movie/include_displayItemListMany.tpl: config/templates/MUVideo/movie/include_displayItemListMany.tpl
src/modules/MUVideo/templates/admin/header.tpl: config/templates/MUVideo/admin/header.tpl
src/modules/MUVideo/templates/admin/footer.tpl: config/templates/MUVideo/admin/footer.tpl
src/modules/MUVideo/templates/user/header.tpl: config/templates/MUVideo/user/header.tpl
src/modules/MUVideo/templates/user/footer.tpl: config/templates/MUVideo/user/footer.tpl
src/modules/MUVideo/templates/admin/inlineRedirectHandler.tpl: config/templates/MUVideo/admin/inlineRedirectHandler.tpl
src/modules/MUVideo/templates/user/inlineRedirectHandler.tpl: config/templates/MUVideo/user/inlineRedirectHandler.tpl
src/modules/MUVideo/templates/collection/edit.tpl: config/templates/MUVideo/collection/edit.tpl
src/modules/MUVideo/templates/collection/inlineRedirectHandler.tpl: config/templates/MUVideo/collection/inlineRedirectHandler.tpl
src/modules/MUVideo/templates/movie/edit.tpl: config/templates/MUVideo/movie/edit.tpl
src/modules/MUVideo/templates/movie/inlineRedirectHandler.tpl: config/templates/MUVideo/movie/inlineRedirectHandler.tpl
src/modules/MUVideo/templates/helper/include_categories_display.tpl: config/templates/MUVideo/helper/include_categories_display.tpl
src/modules/MUVideo/templates/helper/include_categories_edit.tpl: config/templates/MUVideo/helper/include_categories_edit.tpl
src/modules/MUVideo/templates/helper/include_standardfields_display.tpl: config/templates/MUVideo/helper/include_standardfields_display.tpl
src/modules/MUVideo/templates/helper/include_standardfields_edit.tpl: config/templates/MUVideo/helper/include_standardfields_edit.tpl
src/modules/MUVideo/templates/admin/config.tpl: config/templates/MUVideo/admin/config.tpl
src/modules/MUVideo/templates/include_pdfheader.tpl: config/templates/MUVideo/include_pdfheader.tpl
