<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

/**
 * Event handler implementation class for special purposes and 3rd party api support.
 */
abstract class MUVideo_Listener_Base_AbstractThirdParty
{
    
    /**
     * Listener for the `module.content.gettypes` event.
     *
     * This event occurs when the Content module is 'searching' for Content plugins.
     * The subject is an instance of Content_Types.
     * You can register custom content types as well as custom layout types.
     *
     * @param Zikula_Event $event The event instance
     */
    public static function contentGetTypes(Zikula_Event $event)
    {
        // intended is using the add() method to add a plugin like below
        $types = $event->getSubject();
        
        
        // plugin for showing a single item
        $types->add('MUVideo_ContentType_Item');
        
        // plugin for showing a list of multiple items
        $types->add('MUVideo_ContentType_ItemList');
    }
    
    /**
     * Listener for the `module.scribite.editorhelpers` event.
     *
     * This occurs when Scribite adds pagevars to the editor page.
     * MUVideo will use this to add a javascript helper to add custom items.
     *
     * @param Zikula_Event $event The event instance
     */
    public static function getEditorHelpers(Zikula_Event $event)
    {
        // intended is using the add() method to add a helper like below
        $helpers = $event->getSubject();
        
        $helpers->add(
            array(
                'module' => 'MUVideo',
                'type'   => 'javascript',
                'path'   => 'modules/MUVideo/javascript/MUVideo_finder.js'
            )
        );
    }
    
    /**
     * Listener for the `moduleplugin.tinymce.externalplugins` event.
     *
     * Adds external plugin to TinyMCE.
     *
     * @param Zikula_Event $event The event instance
     */
    public static function getTinyMcePlugins(Zikula_Event $event)
    {
        // intended is using the add() method to add a plugin like below
        $plugins = $event->getSubject();
        
        $plugins->add(
            array(
                'name' => 'muvideo',
                'path' => 'modules/MUVideo/docs/scribite/plugins/TinyMce/plugins/muvideo/editor_plugin.js'
            )
        );
    }
    
    /**
     * Listener for the `moduleplugin.ckeditor.externalplugins` event.
     *
     * Adds external plugin to CKEditor.
     *
     * @param Zikula_Event $event The event instance
     */
    public static function getCKEditorPlugins(Zikula_Event $event)
    {
        // intended is using the add() method to add a plugin like below
        $plugins = $event->getSubject();
        
        $plugins->add(
            array(
                'name' => 'muvideo',
                'path' => 'modules/MUVideo/docs/scribite/plugins/CKEditor/vendor/ckeditor/plugins/muvideo/',
                'file' => 'plugin.js',
                'img'  => 'ed_muvideo.gif'
            )
        );
    }
}
