<?php
/**
 * Video.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Michael Ueberschaer <info@homepages-mit-zikula.de>.
 * @link https://homepages-mit-zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace MU\VideoModule\Entity;

use MU\VideoModule\Entity\Base\AbstractPlaylistTranslationEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing playlist translations.
 *
 * This is the concrete translation class for playlist entities.
 *
 * @ORM\Entity(repositoryClass="MU\VideoModule\Entity\Repository\PlaylistTranslationRepository")
 * @ORM\Table(name="mu_video_playlist_translation",
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     }
 * )
 */
class PlaylistTranslationEntity extends BaseEntity
{
    // feel free to add your own methods here
}
