<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.7.0 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing collection translations.
 *
 * This is the concrete translation class for collection entities.
 *
 * @ORM\Entity(repositoryClass="MUVideo_Entity_Repository_CollectionTranslation")
 * @ORM\Table(name="muvideo_collection_translation",
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     }
 * )
 */
class MUVideo_Entity_CollectionTranslation extends MUVideo_Entity_Base_CollectionTranslation
{
    // feel free to add your own methods here
}
