<?php
/**
 * MUVideo.
 *
 * @copyright Michael Ueberschaer (MU)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package MUVideo
 * @author Michael Ueberschaer <kontakt@webdesign-in-bremen.com>.
 * @link http://webdesign-in-bremen.com
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing movie categories.
 *
 * This is the concrete category class for movie entities.
 * @ORM\Entity(repositoryClass="MUVideo_Entity_Repository_MovieCategory")
 * @ORM\Table(name="muvideo_movie_category",
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
 *     }
 * )
 */
class MUVideo_Entity_MovieCategory extends MUVideo_Entity_Base_MovieCategory
{
    // feel free to add your own methods here
}
